# Generated by Django 5.1.2 on 2024-11-05 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(default=datetime.time(2, 18, 19, 887429)),
            preserve_default=False,
        ),
    ]
